name: Scrape turnstile data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 6/2 * * 6'
    - cron: '0 0-4/2 * * 0'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Use Node
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Fetch latest data
      run: node turnstile-scrape.js
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        timestamp=$(date -u --iso-8601=seconds)
        if [[ $(git status --porcelain=v1 2>/dev/null | wc -l) -gt 0 ]]; then echo "{\"timestamp\": \"${timestamp}\"}" > data/timestamp.json; fi
        git add -A
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
